<?php
require_once __DIR__ . '/includes/header.php';
require_login();
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!can_edit_prices()){ flash('danger','No tienes permiso para editar precios.'); redirect_to('catalogo.php'); }
  $id=(int)($_POST['id']??0);
  $data=[(int)$_POST['empresa_id'],$_POST['tipo'],trim($_POST['nombre']),trim($_POST['descripcion']??''),(float)($_POST['precio_base']??0),(int)($_POST['incluye_diseno']??0),(int)($_POST['incluye_instalacion']??0),(int)($_POST['permite_precio_especial']??1),(int)($_POST['activo']??1)];
  try{
    if($id){ $stmt=db()->prepare("UPDATE v2_catalogo_items SET empresa_id=?, tipo=?, nombre=?, descripcion=?, precio_base=?, incluye_diseno=?, incluye_instalacion=?, permite_precio_especial=?, activo=? WHERE id=?"); $stmt->execute(array_merge($data,[$id])); }
    else { $stmt=db()->prepare("INSERT INTO v2_catalogo_items (empresa_id,tipo,nombre,descripcion,precio_base,incluye_diseno,incluye_instalacion,permite_precio_especial,activo) VALUES (?,?,?,?,?,?,?,?,?)"); $stmt->execute($data); }
    flash('success','Catálogo guardado.');
  }catch(Exception $e){ flash('danger','Error: '.$e->getMessage()); }
  redirect_to('catalogo.php');
}
$edit=null; if(isset($_GET['edit'])){ $stmt=db()->prepare("SELECT * FROM v2_catalogo_items WHERE id=?"); $stmt->execute([(int)$_GET['edit']]); $edit=$stmt->fetch(); }
$empresas=empresas();
$rows=db()->query("SELECT c.*, e.nombre empresa FROM v2_catalogo_items c JOIN v2_empresas e ON e.id=c.empresa_id ORDER BY e.nombre,c.tipo,c.nombre")->fetchAll();
function selcat($a,$b){return (string)$a===(string)$b?'selected':'';}
?>
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Catálogo de promociones y productos</h1></div>
<div class="row g-3"><div class="col-lg-8"><div class="card"><div class="card-header">Productos registrados</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Empresa</th><th>Tipo</th><th>Nombre</th><th>Precio</th><th>Incluye</th><th>Activo</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= h($r['empresa']) ?></td><td><?= h($r['tipo']) ?></td><td><strong><?= h($r['nombre']) ?></strong><br><span class="text-muted small"><?= h(mb_strimwidth($r['descripcion']??'',0,120,'...')) ?></span></td><td><?= money($r['precio_base']) ?></td><td><?= $r['incluye_diseno']?'Diseño ':'' ?><?= $r['incluye_instalacion']?'Instalación':'' ?></td><td><?= $r['activo']?'Sí':'No' ?></td><td><?php if(can_edit_prices()): ?><a class="btn btn-sm btn-outline-primary" href="<?= url('catalogo.php?edit='.$r['id']) ?>">Editar</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-header"><?= $edit?'Editar':'Nuevo' ?> producto/promoción</div><div class="card-body"><?php if(can_edit_prices()): ?><form method="post"><input type="hidden" name="id" value="<?= h($edit['id']??'') ?>"><label class="form-label">Empresa</label><select class="form-select mb-2" name="empresa_id"><?php foreach($empresas as $e): ?><option value="<?= $e['id'] ?>" <?= selcat($edit['empresa_id']??'', $e['id']) ?>><?= h($e['nombre']) ?></option><?php endforeach; ?></select><label class="form-label">Tipo</label><select class="form-select mb-2" name="tipo"><option value="promocion">Promoción</option><option value="bandera" <?= selcat($edit['tipo']??'','bandera') ?>>Bandera</option><option value="lona" <?= selcat($edit['tipo']??'','lona') ?>>Lona</option><option value="vinil" <?= selcat($edit['tipo']??'','vinil') ?>>Vinil</option><option value="diseno_extra" <?= selcat($edit['tipo']??'','diseno_extra') ?>>Diseño extra</option><option value="instalacion" <?= selcat($edit['tipo']??'','instalacion') ?>>Instalación</option><option value="articulo" <?= selcat($edit['tipo']??'','articulo') ?>>Artículo</option><option value="otro" <?= selcat($edit['tipo']??'','otro') ?>>Otro</option></select><label class="form-label">Nombre</label><input class="form-control mb-2" name="nombre" value="<?= h($edit['nombre']??'') ?>" required><label class="form-label">Descripción</label><textarea class="form-control mb-2" name="descripcion" rows="4"><?= h($edit['descripcion']??'') ?></textarea><label class="form-label">Precio base</label><input type="number" step="0.01" class="form-control mb-2" name="precio_base" value="<?= h($edit['precio_base']??0) ?>"><div class="row g-2"><div class="col-6"><label class="form-label">Incluye diseño</label><select class="form-select" name="incluye_diseno"><option value="1" <?= selcat($edit['incluye_diseno']??1,1) ?>>Sí</option><option value="0" <?= selcat($edit['incluye_diseno']??'',0) ?>>No</option></select></div><div class="col-6"><label class="form-label">Instalación</label><select class="form-select" name="incluye_instalacion"><option value="1" <?= selcat($edit['incluye_instalacion']??1,1) ?>>Sí</option><option value="0" <?= selcat($edit['incluye_instalacion']??'',0) ?>>No</option></select></div><div class="col-6"><label class="form-label">Precio especial</label><select class="form-select" name="permite_precio_especial"><option value="1">Sí</option><option value="0" <?= selcat($edit['permite_precio_especial']??'',0) ?>>No</option></select></div><div class="col-6"><label class="form-label">Activo</label><select class="form-select" name="activo"><option value="1">Sí</option><option value="0" <?= selcat($edit['activo']??'',0) ?>>No</option></select></div></div><button class="btn btn-primary w-100 mt-3">Guardar</button></form><?php else: ?><p class="text-muted mb-0">Solo Luis, Mafer, Eduardo o administrador pueden editar precios y catálogo.</p><?php endif; ?></div></div></div></div>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
