<?php
require_once __DIR__ . '/includes/bootstrap.php';
require_login();
require_once __DIR__ . '/includes/header.php';
$id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$nota = null; $partidas=[];
if($id){
  $stmt=db()->prepare("SELECT * FROM v2_notas WHERE id=?"); $stmt->execute([$id]); $nota=$stmt->fetch();
  if(!$nota){ flash('danger','Nota no encontrada.'); redirect_to('notas.php'); }
  $stmt=db()->prepare("SELECT * FROM v2_nota_partidas WHERE nota_id=? ORDER BY id"); $stmt->execute([$id]); $partidas=$stmt->fetchAll();
}
$empresas=empresas(); $disenadores=disenadores();
$catalogo=db()->query("SELECT c.*, e.clave empresa_clave FROM v2_catalogo_items c JOIN v2_empresas e ON e.id=c.empresa_id WHERE c.activo=1 ORDER BY e.nombre,c.tipo,c.nombre")->fetchAll();
if(!$partidas) $partidas=[['catalogo_id'=>'','tipo'=>'articulo','descripcion'=>'','cantidad'=>1,'precio_unitario'=>0,'precio_especial'=>0,'costo_estimado_material'=>0,'costo_estimado_mano_obra'=>0,'costo_estimado_maquila'=>0,'costo_estimado_instalacion'=>0,'costo_real_material'=>0,'costo_real_mano_obra'=>0,'costo_real_maquila'=>0,'costo_real_instalacion'=>0]];
function sel($a,$b){return (string)$a===(string)$b?'selected':'';}
function chk($v){return ((int)$v===1)?'checked':'';}
?>
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?= $id?'Editar nota':'Nueva nota' ?></h1><a href="<?= url('notas.php') ?>" class="btn btn-outline-secondary">Volver</a></div>
<form method="post" action="<?= url('nota_guardar.php') ?>" class="mb-4">
<input type="hidden" name="id" value="<?= (int)$id ?>">
<div class="card mb-3"><div class="card-header">Datos generales</div><div class="card-body"><div class="row g-3">
  <div class="col-md-3"><label class="form-label required">Empresa</label><select class="form-select" name="empresa_id" required><?php foreach($empresas as $e): ?><option value="<?= $e['id'] ?>" <?= sel($nota['empresa_id']??'', $e['id']) ?>><?= h($e['nombre']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-3"><label class="form-label required">Folio físico</label><input class="form-control" name="folio" value="<?= h($nota['folio']??'') ?>" required placeholder="Ej. 2719"></div>
  <div class="col-md-3"><label class="form-label required">Fecha</label><input type="date" class="form-control" name="fecha_nota" value="<?= h($nota['fecha_nota']??date('Y-m-d')) ?>" required></div>
  <div class="col-md-3"><label class="form-label">Diseñador</label><select class="form-select" name="disenador_id"><option value="">Sin asignar</option><?php foreach($disenadores as $d): ?><option value="<?= $d['id'] ?>" <?= sel($nota['disenador_id']??'', $d['id']) ?>><?= h($d['nombre']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-4"><label class="form-label required">Cliente</label><input class="form-control" name="cliente_nombre" value="<?= h($nota['cliente_nombre']??'') ?>" required></div>
  <div class="col-md-4"><label class="form-label">Negocio</label><input class="form-control" name="negocio" value="<?= h($nota['negocio']??'') ?>"></div>
  <div class="col-md-4"><label class="form-label">Teléfono</label><input class="form-control" name="telefono" value="<?= h($nota['telefono']??'') ?>"></div>
  <div class="col-md-6"><label class="form-label">Domicilio</label><input class="form-control" name="domicilio" value="<?= h($nota['domicilio']??'') ?>"></div>
  <div class="col-md-3"><label class="form-label">Origen</label><select class="form-select" name="origen"><option value="whatsapp" <?= sel($nota['origen']??'', 'whatsapp') ?>>WhatsApp</option><option value="mostrador" <?= sel($nota['origen']??'mostrador','mostrador') ?>>Mostrador</option><option value="vendedor" <?= sel($nota['origen']??'','vendedor') ?>>Vendedor externo</option><option value="llamada" <?= sel($nota['origen']??'','llamada') ?>>Llamada</option><option value="facebook" <?= sel($nota['origen']??'','facebook') ?>>Facebook</option><option value="otro" <?= sel($nota['origen']??'','otro') ?>>Otro</option></select></div>
  <div class="col-md-3"><label class="form-label">Vendedor / intermediario</label><input class="form-control" name="vendedor_nombre" value="<?= h($nota['vendedor_nombre']??'') ?>"></div>
  <div class="col-md-3"><label class="form-label">Fecha promesa</label><input type="date" class="form-control" name="fecha_promesa" value="<?= h($nota['fecha_promesa']??'') ?>"></div>
  <div class="col-md-3"><label class="form-label">Fecha instalación</label><input type="date" class="form-control" name="fecha_instalacion" value="<?= h($nota['fecha_instalacion']??'') ?>"></div>
  <div class="col-md-3"><label class="form-label">Factura</label><select class="form-select" name="requiere_factura"><option value="0" <?= sel($nota['requiere_factura']??0,0) ?>>No</option><option value="1" <?= sel($nota['requiere_factura']??0,1) ?>>Sí</option></select></div>
  <div class="col-12"><label class="form-label">Observaciones</label><textarea class="form-control" name="observaciones" rows="2"><?= h($nota['observaciones']??'') ?></textarea></div>
</div></div></div>

<div class="card mb-3"><div class="card-header d-flex justify-content-between align-items-center"><span>Partidas / productos</span><button type="button" class="btn btn-sm btn-outline-primary" onclick="addPartida()">Agregar partida</button></div><div class="card-body">
  <div id="partidas-wrap">
  <?php foreach($partidas as $p): ?>
    <div class="partida-row border rounded-3 p-3 mb-3 bg-light">
      <input type="hidden" name="partida_id[]" value="<?= h($p['id']??'') ?>">
      <div class="row g-2">
        <div class="col-md-3"><label class="form-label">Catálogo</label><select class="form-select catalogo-select" name="catalogo_id[]"><option value="">Partida libre</option><?php foreach($catalogo as $c): ?><option value="<?= $c['id'] ?>" data-tipo="<?= h($c['tipo']) ?>" data-desc="<?= h($c['descripcion']) ?>" data-price="<?= h($c['precio_base']) ?>" <?= sel($p['catalogo_id']??'', $c['id']) ?>><?= strtoupper(h($c['empresa_clave'])) ?> · <?= h($c['nombre']) ?> · <?= money($c['precio_base']) ?></option><?php endforeach; ?></select></div>
        <div class="col-md-2"><label class="form-label">Tipo</label><select class="form-select part-tipo" name="tipo[]"><option value="promocion" <?= sel($p['tipo']??'','promocion') ?>>Promoción</option><option value="bandera" <?= sel($p['tipo']??'','bandera') ?>>Bandera</option><option value="lona" <?= sel($p['tipo']??'','lona') ?>>Lona</option><option value="vinil" <?= sel($p['tipo']??'','vinil') ?>>Vinil</option><option value="diseno_extra" <?= sel($p['tipo']??'','diseno_extra') ?>>Diseño extra</option><option value="instalacion" <?= sel($p['tipo']??'','instalacion') ?>>Instalación</option><option value="articulo" <?= sel($p['tipo']??'articulo','articulo') ?>>Artículo</option><option value="otro" <?= sel($p['tipo']??'','otro') ?>>Otro</option></select></div>
        <div class="col-md-4"><label class="form-label required">Descripción</label><textarea class="form-control part-desc" name="descripcion[]" rows="2" required><?= h($p['descripcion']??'') ?></textarea></div>
        <div class="col-md-1"><label class="form-label">Cant.</label><input type="number" step="0.01" class="form-control part-cantidad" name="cantidad[]" value="<?= h($p['cantidad']??1) ?>"></div>
        <div class="col-md-2"><label class="form-label">Precio unit.</label><input type="number" step="0.01" class="form-control part-precio" name="precio_unitario[]" value="<?= h($p['precio_unitario']??0) ?>"></div>
        <div class="col-md-2"><label class="form-label">Precio especial</label><select class="form-select" name="precio_especial[]"><option value="0" <?= sel($p['precio_especial']??0,0) ?>>No</option><option value="1" <?= sel($p['precio_especial']??0,1) ?>>Sí</option></select></div>
        <div class="col-md-2"><label class="form-label">Subtotal</label><div class="form-control bg-white part-total">$0.00 MXN</div></div>
        <?php if(can_finance()): ?>
        <div class="col-12"><div class="row g-2"><div class="col-md-3"><label class="form-label">Costo est. material</label><input type="number" step="0.01" class="form-control" name="costo_estimado_material[]" value="<?= h($p['costo_estimado_material']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo est. mano obra</label><input type="number" step="0.01" class="form-control" name="costo_estimado_mano_obra[]" value="<?= h($p['costo_estimado_mano_obra']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo est. maquila</label><input type="number" step="0.01" class="form-control" name="costo_estimado_maquila[]" value="<?= h($p['costo_estimado_maquila']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo est. instalación</label><input type="number" step="0.01" class="form-control" name="costo_estimado_instalacion[]" value="<?= h($p['costo_estimado_instalacion']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo real material</label><input type="number" step="0.01" class="form-control" name="costo_real_material[]" value="<?= h($p['costo_real_material']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo real mano obra</label><input type="number" step="0.01" class="form-control" name="costo_real_mano_obra[]" value="<?= h($p['costo_real_mano_obra']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo real maquila</label><input type="number" step="0.01" class="form-control" name="costo_real_maquila[]" value="<?= h($p['costo_real_maquila']??0) ?>"></div><div class="col-md-3"><label class="form-label">Costo real instalación</label><input type="number" step="0.01" class="form-control" name="costo_real_instalacion[]" value="<?= h($p['costo_real_instalacion']??0) ?>"></div></div></div>
        <?php endif; ?>
        <div class="col-12"><button type="button" class="btn btn-sm btn-outline-danger" onclick="removePartida(this)">Quitar partida</button></div>
      </div>
    </div>
  <?php endforeach; ?>
  </div>
  <div class="text-end h5">Total previo: <span id="total-preview">$0.00 MXN</span></div>
</div></div>

<div class="card mb-3"><div class="card-header">Estados iniciales</div><div class="card-body"><div class="row g-3">
  <div class="col-md-2"><label class="form-label">Contacto</label><select name="estado_contacto" class="form-select"><option value="pendiente" <?= sel($nota['estado_contacto']??'pendiente','pendiente') ?>>Pendiente</option><option value="contactado" <?= sel($nota['estado_contacto']??'','contactado') ?>>Contactado</option><option value="cliente_no_contesta" <?= sel($nota['estado_contacto']??'','cliente_no_contesta') ?>>Cliente no contesta</option><option value="no_aplica" <?= sel($nota['estado_contacto']??'','no_aplica') ?>>No aplica</option></select></div>
  <div class="col-md-2"><label class="form-label">Diseño</label><select name="estado_diseno" class="form-select"><option value="sin_asignar" <?= sel($nota['estado_diseno']??'sin_asignar','sin_asignar') ?>>Sin asignar</option><option value="pendiente_contacto" <?= sel($nota['estado_diseno']??'','pendiente_contacto') ?>>Pendiente contacto</option><option value="en_diseno" <?= sel($nota['estado_diseno']??'','en_diseno') ?>>En diseño</option><option value="en_aprobacion" <?= sel($nota['estado_diseno']??'','en_aprobacion') ?>>En aprobación</option><option value="aprobado" <?= sel($nota['estado_diseno']??'','aprobado') ?>>Aprobado</option><option value="no_aplica" <?= sel($nota['estado_diseno']??'','no_aplica') ?>>No aplica</option></select></div>
  <div class="col-md-2"><label class="form-label">Aprob. impresión</label><select name="estado_aprobacion_impresion" class="form-select"><option value="pendiente" <?= sel($nota['estado_aprobacion_impresion']??'pendiente','pendiente') ?>>Pendiente</option><option value="autorizada" <?= sel($nota['estado_aprobacion_impresion']??'','autorizada') ?>>Autorizada</option><option value="rechazada" <?= sel($nota['estado_aprobacion_impresion']??'','rechazada') ?>>Rechazada</option><option value="no_aplica" <?= sel($nota['estado_aprobacion_impresion']??'','no_aplica') ?>>No aplica</option></select></div>
  <div class="col-md-2"><label class="form-label">Producción</label><select name="estado_produccion" class="form-select"><option value="pendiente" <?= sel($nota['estado_produccion']??'pendiente','pendiente') ?>>Pendiente</option><option value="para_imprimir" <?= sel($nota['estado_produccion']??'','para_imprimir') ?>>Para imprimir</option><option value="impresa" <?= sel($nota['estado_produccion']??'','impresa') ?>>Impresa</option><option value="sublimada" <?= sel($nota['estado_produccion']??'','sublimada') ?>>Sublimada</option><option value="en_costura" <?= sel($nota['estado_produccion']??'','en_costura') ?>>En costura</option><option value="terminada" <?= sel($nota['estado_produccion']??'','terminada') ?>>Terminada</option><option value="problema" <?= sel($nota['estado_produccion']??'','problema') ?>>Problema</option><option value="no_aplica" <?= sel($nota['estado_produccion']??'','no_aplica') ?>>No aplica</option></select></div>
  <div class="col-md-2"><label class="form-label">Instalación</label><select name="estado_instalacion" class="form-select"><option value="no_aplica" <?= sel($nota['estado_instalacion']??'no_aplica','no_aplica') ?>>No aplica</option><option value="pendiente" <?= sel($nota['estado_instalacion']??'','pendiente') ?>>Pendiente</option><option value="programada" <?= sel($nota['estado_instalacion']??'','programada') ?>>Programada</option><option value="en_instalacion" <?= sel($nota['estado_instalacion']??'','en_instalacion') ?>>En instalación</option><option value="instalada" <?= sel($nota['estado_instalacion']??'','instalada') ?>>Instalada</option></select></div>
  <div class="col-md-2"><label class="form-label">Entrega</label><select name="estado_entrega" class="form-select"><option value="pendiente" <?= sel($nota['estado_entrega']??'pendiente','pendiente') ?>>Pendiente</option><option value="lista" <?= sel($nota['estado_entrega']??'','lista') ?>>Lista</option><option value="entregada" <?= sel($nota['estado_entrega']??'','entregada') ?>>Entregada</option><option value="cancelada" <?= sel($nota['estado_entrega']??'','cancelada') ?>>Cancelada</option></select></div>
</div></div></div>
<div class="d-flex gap-2 justify-content-end"><a class="btn btn-outline-secondary" href="<?= url('notas.php') ?>">Cancelar</a><button class="btn btn-primary">Guardar nota</button></div>
</form>
<template id="partida-template"><div class="partida-row border rounded-3 p-3 mb-3 bg-light"><div class="row g-2"><div class="col-md-3"><label class="form-label">Catálogo</label><select class="form-select catalogo-select" name="catalogo_id[]"><option value="">Partida libre</option><?php foreach($catalogo as $c): ?><option value="<?= $c['id'] ?>" data-tipo="<?= h($c['tipo']) ?>" data-desc="<?= h($c['descripcion']) ?>" data-price="<?= h($c['precio_base']) ?>"><?= strtoupper(h($c['empresa_clave'])) ?> · <?= h($c['nombre']) ?> · <?= money($c['precio_base']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Tipo</label><select class="form-select part-tipo" name="tipo[]"><option value="articulo">Artículo</option><option value="promocion">Promoción</option><option value="bandera">Bandera</option><option value="lona">Lona</option><option value="vinil">Vinil</option><option value="diseno_extra">Diseño extra</option><option value="instalacion">Instalación</option><option value="otro">Otro</option></select></div><div class="col-md-4"><label class="form-label required">Descripción</label><textarea class="form-control part-desc" name="descripcion[]" rows="2" required></textarea></div><div class="col-md-1"><label class="form-label">Cant.</label><input type="number" step="0.01" class="form-control part-cantidad" name="cantidad[]" value="1"></div><div class="col-md-2"><label class="form-label">Precio unit.</label><input type="number" step="0.01" class="form-control part-precio" name="precio_unitario[]" value="0"></div><div class="col-md-2"><label class="form-label">Precio especial</label><select class="form-select" name="precio_especial[]"><option value="0">No</option><option value="1">Sí</option></select></div><div class="col-md-2"><label class="form-label">Subtotal</label><div class="form-control bg-white part-total">$0.00 MXN</div></div><?php if(can_finance()): ?><input type="hidden" name="costo_estimado_material[]" value="0"><input type="hidden" name="costo_estimado_mano_obra[]" value="0"><input type="hidden" name="costo_estimado_maquila[]" value="0"><input type="hidden" name="costo_estimado_instalacion[]" value="0"><input type="hidden" name="costo_real_material[]" value="0"><input type="hidden" name="costo_real_mano_obra[]" value="0"><input type="hidden" name="costo_real_maquila[]" value="0"><input type="hidden" name="costo_real_instalacion[]" value="0"><?php endif; ?><div class="col-12"><button type="button" class="btn btn-sm btn-outline-danger" onclick="removePartida(this)">Quitar partida</button></div></div></div></template>
<script>calcPartidas();</script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
