<?php
require_once __DIR__ . '/includes/bootstrap.php';
require_login();
require_once __DIR__ . '/includes/header.php';
if(!can_finance()){ flash('danger','No tienes permiso para reportes financieros.'); redirect_to('index.php'); }
$empresa=$_GET['empresa']??''; $desde=$_GET['desde']??date('Y-m-01'); $hasta=$_GET['hasta']??date('Y-m-d');
$params=[$desde,$hasta]; $where="n.fecha_nota BETWEEN ? AND ?";
if($empresa!==''){ $where.=" AND e.clave=?"; $params[]=$empresa; }
$stmt=db()->prepare("SELECT e.nombre empresa, COUNT(*) notas, COALESCE(SUM(n.total),0) total, COALESCE(SUM(n.pagado),0) pagado, COALESCE(SUM(n.saldo),0) saldo, COALESCE(SUM(n.costo_real_total),0) costo_real, COALESCE(SUM(n.comision_total),0) comision, COALESCE(SUM(n.merma_total),0) merma, COALESCE(SUM(n.utilidad_real),0) utilidad FROM v2_notas n JOIN v2_empresas e ON e.id=n.empresa_id WHERE $where GROUP BY e.id,e.nombre ORDER BY e.nombre");
$stmt->execute($params); $res=$stmt->fetchAll();
$params2=[$desde,$hasta]; $where2="p.fecha_pago BETWEEN ? AND ?"; if($empresa!==''){ $where2.=" AND e.clave=?"; $params2[]=$empresa; }
$stmt=db()->prepare("SELECT e.nombre empresa, p.forma_pago, p.forma_pago_otro, DATE(p.fecha_pago) fecha, SUM(CASE WHEN p.concepto='devolucion' THEN -p.monto ELSE p.monto END) total FROM v2_pagos p JOIN v2_empresas e ON e.id=p.empresa_id WHERE $where2 GROUP BY e.nombre,p.forma_pago,p.forma_pago_otro,DATE(p.fecha_pago) ORDER BY fecha DESC,empresa,forma_pago");
$stmt->execute($params2); $pagos=$stmt->fetchAll();
$stmt=db()->prepare("SELECT e.nombre empresa, u.nombre disenador, c.estado, SUM(c.monto) total, COUNT(*) cantidad FROM v2_comisiones c JOIN v2_empresas e ON e.id=c.empresa_id JOIN v2_usuarios u ON u.id=c.disenador_id WHERE (c.fecha_semana BETWEEN ? AND ? OR c.fecha_pago BETWEEN ? AND ?)".($empresa!==''?" AND e.clave=?":"")." GROUP BY e.nombre,u.nombre,c.estado ORDER BY e.nombre,u.nombre,c.estado");
$cp=[$desde,$hasta,$desde,$hasta]; if($empresa!=='') $cp[]=$empresa; $stmt->execute($cp); $coms=$stmt->fetchAll();
?>
<h1 class="h3 mb-3">Reportes</h1>
<form class="card card-body mb-3 no-print"><div class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">Empresa</label><select class="form-select" name="empresa"><option value="">Todas</option><option value="viprint" <?= $empresa==='viprint'?'selected':'' ?>>ViPrint</option><option value="imagen" <?= $empresa==='imagen'?'selected':'' ?>>Imagen</option></select></div><div class="col-md-3"><label class="form-label">Desde</label><input type="date" class="form-control" name="desde" value="<?= h($desde) ?>"></div><div class="col-md-3"><label class="form-label">Hasta</label><input type="date" class="form-control" name="hasta" value="<?= h($hasta) ?>"></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Filtrar</button></div></div></form>
<div class="card mb-3"><div class="card-header">Resumen por empresa</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Empresa</th><th>Notas</th><th>Total vendido</th><th>Pagado</th><th>Saldo</th><th>Costo real</th><th>Comisión</th><th>Merma</th><th>Utilidad real</th></tr></thead><tbody><?php foreach($res as $r): ?><tr><td><?= h($r['empresa']) ?></td><td><?= (int)$r['notas'] ?></td><td><?= money($r['total']) ?></td><td><?= money($r['pagado']) ?></td><td><?= money($r['saldo']) ?></td><td><?= money($r['costo_real']) ?></td><td><?= money($r['comision']) ?></td><td><?= money($r['merma']) ?></td><td><strong><?= money($r['utilidad']) ?></strong></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="row g-3"><div class="col-lg-7"><div class="card"><div class="card-header">Ingresos por fecha y método de pago</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Fecha</th><th>Empresa</th><th>Método</th><th>Total</th></tr></thead><tbody><?php foreach($pagos as $p): ?><tr><td><?= date_mx($p['fecha']) ?></td><td><?= h($p['empresa']) ?></td><td><?= h($p['forma_pago']) ?><?= $p['forma_pago_otro']?' / '.h($p['forma_pago_otro']):'' ?></td><td><?= money($p['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div><div class="col-lg-5"><div class="card"><div class="card-header">Comisiones por diseñador</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Empresa</th><th>Diseñador</th><th>Estado</th><th>Cantidad</th><th>Total</th></tr></thead><tbody><?php foreach($coms as $c): ?><tr><td><?= h($c['empresa']) ?></td><td><?= h($c['disenador']) ?></td><td><?= h($c['estado']) ?></td><td><?= (int)$c['cantidad'] ?></td><td><?= money($c['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div></div>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
